-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bookings
(
    booking_id integer NOT NULL DEFAULT nextval('bookings_booking_id_seq'::regclass),
    flight_id integer NOT NULL,
    user_id integer NOT NULL,
    passportnumber character varying(250) COLLATE pg_catalog."default" NOT NULL,
    national_id_number character varying(250) COLLATE pg_catalog."default" NOT NULL,
    passengerfirstname character varying(250) COLLATE pg_catalog."default",
    passengermiddlename character varying(250) COLLATE pg_catalog."default",
    passengerlastname character varying(250) COLLATE pg_catalog."default",
    title character varying(10) COLLATE pg_catalog."default",
    travelclass character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT bookings_pkey PRIMARY KEY (booking_id)
);

CREATE TABLE IF NOT EXISTS public.cities
(
    city_id integer NOT NULL DEFAULT nextval('cities_city_id_seq'::regclass),
    city character varying(250) COLLATE pg_catalog."default" NOT NULL,
    code character varying(20) COLLATE pg_catalog."default",
    type character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT cities_pkey PRIMARY KEY (city_id)
);

CREATE TABLE IF NOT EXISTS public.flights
(
    flight_id integer NOT NULL DEFAULT nextval('flights_flight_id_seq'::regclass),
    flightnumber character varying(250) COLLATE pg_catalog."default" NOT NULL,
    departuretime time without time zone NOT NULL,
    departurecity integer NOT NULL,
    arrivalcity integer NOT NULL,
    flightdate date NOT NULL,
    economyprice integer,
    businessprice integer,
    arrivaltime time without time zone,
    arrivaldate date,
    flightstatus character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT flights_pkey PRIMARY KEY (flight_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL DEFAULT nextval('users_user_id_seq'::regclass),
    username character varying(250) COLLATE pg_catalog."default" NOT NULL,
    password character varying(250) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_flight_id_fkey FOREIGN KEY (flight_id)
    REFERENCES public.flights (flight_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.flights
    ADD CONSTRAINT flights_arrivalcity_fkey FOREIGN KEY (arrivalcity)
    REFERENCES public.cities (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.flights
    ADD CONSTRAINT flights_departurecity_fkey FOREIGN KEY (departurecity)
    REFERENCES public.cities (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;